---

# Example sandbox configuration
# for single server community
# installs

- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    edx_platform_version: "{{ COMMON_BRANCH_INSTALL_EDX_PLATFORM }}"
  vars_files:
    - "./roles/insights/defaults/main.yml"
    - "./roles/edxapp/defaults/main.yml"
    - "./roles/edx_notes_api/defaults/main.yml"
    - "./roles/analytics_pipeline/defaults/main.yml"
    - "./roles/analytics_api/defaults/main.yml"
    - "./roles/hive/defaults/main.yml"
    - "./roles/credentials/defaults/main.yml"
    - "./roles/discovery/defaults/main.yml"
    - "./roles/forum/defaults/main.yml"
    - "./roles/xqueue/defaults/main.yml"
  roles:
    - role: edxlocal
    - role: memcache
    - role: mongo_3_2
    - role: rabbitmq
    - analytics_api
    - oraclejdk
    - role: elasticsearch
    - edx_ansible