---

# Stateless app server configuration, designed to be used with external mysql,
# mongo, rabbitmq, and elasticsearch services.

- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True

  vars:
    migrate_db: 'yes'
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    ENABLE_ECOMMERCE: False  # Disable ecommerce by default
    EDXAPP_MONGO_HOSTS: "{{COMMON_IP_DATASTORE}}"
    EDXAPP_MYSQL_HOST: "{{COMMON_IP_DATASTORE}}"
    EDXAPP_MYSQL_CSMH_HOST: "{{COMMON_IP_DATASTORE}}"
    EDXAPP_ELASTIC_SEARCH_CONFIG:
      - host: "{{COMMON_IP_DATASTORE}}"
        port: 9200
    EDXAPP_MEMCACHE: ["{{COMMON_IP_DATASTORE}}:11211"]
    EDXAPP_RABBIT_HOSTNAME: "{{COMMON_IP_DATASTORE}}"
    FORUM_MONGO_HOSTS: "{{COMMON_IP_DATASTORE}}"
    FORUM_ELASTICSEARCH_HOST: "{{COMMON_IP_DATASTORE}}"
    XQUEUE_RABBITMQ_HOSTNAME: "{{COMMON_IP_DATASTORE}}"
    XQUEUE_MYSQL_HOST: "{{COMMON_IP_DATASTORE}}"
  roles:

    # Ensure we have no known security vulnerabilities
    - security

    
    # Nginx reverse proxy
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - xqueue
      nginx_default_sites:
      - lms

    # Main EdX application
    # https://github.com/edx/edx-platform
    - role: edxapp
      celery_worker: True
    - edxapp

    # Discussion forums
    # https://github.com/edx/cs_comments_service
    - forum
    
    # Notes edx-notes-api
    # https://github.com/edx/edx-notes-api
    - edx_notes_api

    # Notifications service
    # https://github.com/edx/notifier
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: '5'

    # XQueue interface for communicating with external grader services
    # https://github.com/edx/xqueue
    - role: xqueue
      update_users: True

    # Certificate generation
    # https://github.com/edx/edx-certificates
    - certs

    # Email sending
    - postfix_queue
